---
- name: Install apache
  apt: 
    name: apache2
    state: present

- name: Stop apache2
  service:
    name: apache2
    state: stopped

- name: Disable default config 
  command: a2dissite 000-default.conf

- copy: 
    src: configs/raspifarm.conf
    dest: /etc/apache2/sites-available/raspifarm.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Enable raspifarm config
  command: a2ensite raspifarm.conf

- name: Start apache
  service:
    name: apache2
    state: started

- name: Reload apache
  service: 
    name: apache2
    state: reloaded
