---
- name: 'Copy .bash_profile to home'
  copy: 
    src: configs/bash_profile
    dest: "{{ home_dir }}/.bash_profile"
    owner: farmer
    group: admin
    mode: 0644
    backup: yes

- name: "Include .bash_profile in .bashrc"
  lineinfile: 
    dest: "/home/farmer/{{ item }}" 
    line: "if [ -f ~/.bash_profile ]; then . ~/.bash_profile; fi"
    state: present
  with_items:
    - ".bashrc"
    - ".profile"