---
    # dnsmasq 
- name: Install dnsmasq
  apt: 
    name: dnsmasq
    state: present

- name: Stop dnsmasq
  service:
    name: dnsmasq
    state: stopped

- copy: 
    src: configs/dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Start dnsmasq
  service:
    name: dnsmasq
    state: started