---
- name: scipy
  apt: 
    name: "{{ item }}"
    state: present
    force: yes
  with_items: 
    - "python-numpy"
    - "python-scipy"
    - "python-matplotlib"
    # - "ipython"
    # - "python-pandas"
    # - "python-sympy"
    # - "python-nose"